"""add_warehouse_id_to_purchase

Revision ID: 0ab349da903f
Revises: add_cost_price_to_part
Create Date: 2025-03-08 17:31:42.829241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab349da903f'
down_revision = 'add_cost_price_to_part'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_purchase_warehouse_id', 'warehouse', ['warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_warehouse_id', type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
