"""Remove void functionality from loans

Revision ID: 2ecc2e870d8e
Revises: a999a6c532f9
Create Date: 2025-07-12 11:16:58.369154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecc2e870d8e'
down_revision = 'a999a6c532f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_void')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_loan_void_approved_by_id', type_='foreignkey')
        batch_op.drop_column('void_approved_at')
        batch_op.drop_column('voided_by_id')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_at')
        batch_op.drop_column('void_approved_by_id')
        batch_op.drop_column('voided')
        batch_op.drop_column('void_approval_status')
        batch_op.drop_column('void_approval_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('void_approval_required', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('void_approval_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('voided', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('void_approved_by_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('voided_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('voided_by_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('void_approved_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_loan_void_approved_by_id', 'user', ['void_approved_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['voided_by_id'], ['id'])

    op.create_table('loan_void',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_id', sa.INTEGER(), nullable=False),
    sa.Column('voided_by_id', sa.INTEGER(), nullable=False),
    sa.Column('voided_at', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('void_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('items_restored', sa.INTEGER(), nullable=True),
    sa.Column('payments_reversed', sa.INTEGER(), nullable=True),
    sa.Column('total_amount_reversed', sa.FLOAT(), nullable=True),
    sa.Column('approval_required', sa.BOOLEAN(), nullable=True),
    sa.Column('approved_by_id', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('approval_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
