"""Add enhanced void fields to loan model

Revision ID: a999a6c532f9
Revises: 
Create Date: 2025-07-12 10:53:21.922782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a999a6c532f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_void',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('voided_by_id', sa.Integer(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('void_type', sa.String(length=20), nullable=True),
    sa.Column('items_restored', sa.Integer(), nullable=True),
    sa.Column('payments_reversed', sa.Integer(), nullable=True),
    sa.Column('total_amount_reversed', sa.Float(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('void_approval_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('void_approval_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('void_approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('void_approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['void_approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('void_approved_at')
        batch_op.drop_column('void_approved_by_id')
        batch_op.drop_column('void_approval_status')
        batch_op.drop_column('void_approval_required')

    op.drop_table('loan_void')
    # ### end Alembic commands ###
